### ISSUE TITLE
Jetpack compose support !!

### ISSUE THREAD

**Issue by KapilYadav-dev** [CRED-CLUB/neopop-android#25]
Hey team, thanks for giving so wonderful libraries to our arsenals.
So, any plans for Jetpack support ?

**Comment by bansalayush** [comment]
Compose version of the neopop library is in the works and will be out soon. Be on the look out in the near future!

**Comment by Marchuck** [comment]
@KapilYadav-dev 
I made a pet project inspired by NeoPOP where simple button is implemented on top of Compose's Modifier API

Button content, in most cases `Text(...)` can be passed as `@Composable`

Feel free to contribute!

https://github.com/Marchuck/NeoPOP-Compose
