### ISSUE TITLE
It is Worst UI if user cant even install it in there apps

### ISSUE THREAD

**Issue by blacklighter07** [CRED-CLUB/neopop-android#31]
It is not showing any error when I am implementing things in gradle but after that it is of no use in my project neither it is showing text nor option to write text, and it is new so I couldn't find solution to this on internet give a step by step manual for this theme otherwise its worst for me.

**Comment by nikhilpanju** [comment]
Hey! Can you check the sample app provided in this repo for examples?
You can clone the repo and build the sample and use that as a reference.

**Comment by blacklighter07** [comment]
Thank you for your response

-- 


Disclaimer:- This footer text is to convey that this email is sent by one 
of the users of IITH. So, do not mark it as SPAM.

**Comment by blacklighter07** [comment]
My issue is not resolved and i am still facing problem can u just make a demo or write that will it be implemented  by simply writing code in xml or do i have to do changes in .kt files too
